#####################################################################
#### Please don't change this file. Use component.mk instead ####
#####################################################################

ifndef SMING_HOME
$(error SMING_HOME is not set: please configure it as an environment variable)
endif

# This is a Host-only application
SMING_ARCH := Host
STRICT := 1

include $(SMING_HOME)/project.mk
